[project]
name = "notte-sdk"
version = "1.4.4.dev"
description = "The SDK for Notte"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_sdk", from = "src" },
]

requires-python = ">=3.11"
dependencies = [
    "halo>=0.0.28",
    "notte-core==1.4.4.dev",
    "websockets>=13.1",
    "typer>=0.9.0",
    "tqdm>=4.66.0",
]

[project.optional-dependencies]
playwright = [
    "playwright~=1.55",
]

[project.scripts]
notte-workflow = "notte_sdk.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
